/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JButton;
import logic.controllers.InsertionSortStrategy;
import logic.controllers.MergeStrategy;
import logic.controllers.QuickSortStrategy;
import logic.controllers.SelectionSortStrategy;

/**
 *
 * @author Sebastian Rodriguez
 * @email roskoff@hotmail.es
 * @linkedin https://uy.linkedin.com/in/sebastianr88
 *
 */

public class ISortResult extends javax.swing.JInternalFrame {

    /**
     * Creates new form ISortResult
     */
    public ISortResult() {
        initComponents();
    }
    
    public JButton getjBPreviousIsortForm(){
        return this.jButtonPrevious;
    }
     
    public void setInputText(String input){
        this.jLabelInputResult.setText(input);
    }
    
    public void setInputResultText(String result){
        this.jLabelResult.setText(result);
    }
    
    public void setMergeTimeResult(String result){
        this.jLabelMergeResult.setText("");
        this.jLabelMergeResult.setText(result);
    }
   
    public void setQuickSortTimeResult(String result){
        this.jLabelQuickSortResult.setText("");
        this.jLabelQuickSortResult.setText(result);
    }
    
    public void setSelectionSortTimeResult(String result){
        this.jLabelSelectionSortResult.setText("");
        this.jLabelSelectionSortResult.setText(result);
    }
    
    public void setInsertionSortTimeResult(String result){
        this.jLabelInsertionResult.setText("");
        this.jLabelInsertionResult.setText(result);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelResultText = new javax.swing.JLabel();
        jLabelResult = new javax.swing.JLabel();
        jLabelMerge = new javax.swing.JLabel();
        jLabelMergeResult = new javax.swing.JLabel();
        jLabelQuickSort = new javax.swing.JLabel();
        jLabelQuickSortResult = new javax.swing.JLabel();
        jLabelSelectionSort = new javax.swing.JLabel();
        jLabelSelectionSortResult = new javax.swing.JLabel();
        jLabelInsertionSort = new javax.swing.JLabel();
        jLabelInsertionResult = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonPrevious = new javax.swing.JButton();
        jLabelInputText = new javax.swing.JLabel();
        jLabelInputResult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Result");
        setToolTipText("");

        jLabelResultText.setText("Result: ");

        jLabelResult.setText("jLabelResult");

        jLabelMerge.setText("Merge Sort:");

        jLabelMergeResult.setText("JLabelMerge");

        jLabelQuickSort.setText("Quick Sort:");

        jLabelQuickSortResult.setText("JLabelQuickSort");

        jLabelSelectionSort.setText("Selection Sort:");

        jLabelSelectionSortResult.setText("JLabelSelectionSort");

        jLabelInsertionSort.setText("Insertion Sort:");

        jLabelInsertionResult.setText("JLabelInsertionSort");

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonPrevious.setText("Previous");
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });

        jLabelInputText.setText("Input: ");

        jLabelInputResult.setText("jLabelInput");

        jLabel1.setText("Sorting time results:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelResultText)
                    .addComponent(jLabelInputText))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInputResult)
                    .addComponent(jLabelResult))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPrevious)
                .addGap(30, 30, 30)
                .addComponent(jButtonExit)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelInsertionSort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelInsertionResult))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSelectionSort)
                                    .addComponent(jLabelQuickSort))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelQuickSortResult)
                                    .addComponent(jLabelSelectionSortResult)
                                    .addComponent(jLabelMergeResult))))
                        .addGap(138, 138, 138))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMerge)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInputText)
                    .addComponent(jLabelInputResult))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResult)
                    .addComponent(jLabelResultText))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMerge)
                    .addComponent(jLabelMergeResult))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuickSortResult)
                    .addComponent(jLabelQuickSort))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPrevious)
                            .addComponent(jButtonExit))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSelectionSort)
                            .addComponent(jLabelSelectionSortResult))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInsertionResult)
                            .addComponent(jLabelInsertionSort))
                        .addGap(31, 160, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPreviousActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelInputResult;
    private javax.swing.JLabel jLabelInputText;
    private javax.swing.JLabel jLabelInsertionResult;
    private javax.swing.JLabel jLabelInsertionSort;
    private javax.swing.JLabel jLabelMerge;
    private javax.swing.JLabel jLabelMergeResult;
    private javax.swing.JLabel jLabelQuickSort;
    private javax.swing.JLabel jLabelQuickSortResult;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelResultText;
    private javax.swing.JLabel jLabelSelectionSort;
    private javax.swing.JLabel jLabelSelectionSortResult;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
